**서브쿼리와 그룹바이 다중조건**

SELECT A.CART_ID FROM (
SELECT CART_ID, NAME FROM CART_PRODUCTS
GROUP BY CART_ID, NAME
HAVING NAME IN ('Milk', 'Yogurt')
) A
GROUP BY A.CART_ID
HAVING COUNT(A.CART_ID) > 1
ORDER BY A.CART_ID;